import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { test } from 'node:test';
import {
  collectLegacyBrowserCoverage,
  collectManagementBrowserCoverage,
  driverForBrowserWorkflow,
  prepareLegacyRuntime,
} from '../tools/coverage/browser-legacy.mjs';
import { replayBrowserCoverage } from '../tools/coverage/browser-evidence.mjs';

test('legacy adapter selects only the existing assertion drivers', () => {
  assert.equal(driverForBrowserWorkflow('legacy'), 'tools/verify-ui-browser.mjs');
  assert.equal(driverForBrowserWorkflow('management'), 'tools/verify-management-browser.mjs');
  assert.throws(() => driverForBrowserWorkflow('unknown'), /UNKNOWN_BROWSER_WORKFLOW/);
});

test('legacy runtime preparation rejects changed source before materializing generated bytes', async (t) => {
  const root = process.env.AF_QUALIFIED_BROWSER_CANDIDATE;
  const prepared = process.env.AF_QUALIFIED_BROWSER_PREPARED;
  assert.ok(root && prepared, 'qualified candidate and prepared paths required');
  const manifest = JSON.parse(readFileSync(resolve(prepared, 'manifest.json')));
  const generated = JSON.parse(readFileSync(resolve(prepared, 'generated.json')));
  const output = resolve(
    process.env.AF_QUALIFIED_BROWSER_OUTPUT || t.name,
    `negative-runtime-${Date.now()}-${Math.random().toString(16).slice(2)}`,
  );
  const altered = structuredClone(generated);
  altered['docs/management/dashboard/app.js'].code += '\n';
  await assert.rejects(
    prepareLegacyRuntime({
      root,
      manifest,
      generated: altered,
      outputDirectory: output,
      workflow: 'management',
    }),
    /generated source/,
  );
});

test('production Vite preparation leaves the exact generated source-map graph immutable', async (t) => {
  const root = process.env.AF_QUALIFIED_BROWSER_CANDIDATE;
  const prepared = process.env.AF_QUALIFIED_BROWSER_PREPARED;
  assert.ok(root && prepared, 'qualified candidate and prepared paths required');
  const manifest = JSON.parse(readFileSync(resolve(prepared, 'manifest.json')));
  const generated = JSON.parse(readFileSync(resolve(prepared, 'generated.json')));
  const before = createHash('sha256').update(JSON.stringify(generated)).digest('hex');
  const output = resolve(
    process.env.AF_QUALIFIED_BROWSER_OUTPUT || t.name,
    `generated-immutable-${Date.now()}-${Math.random().toString(16).slice(2)}`,
  );
  await prepareLegacyRuntime({ root, manifest, generated, outputDirectory: output, workflow: 'legacy' });
  assert.equal(createHash('sha256').update(JSON.stringify(generated)).digest('hex'), before);
});

test(
  'existing legacy and management assertion drivers run through the shared browser lifecycle',
  { skip: !process.env.AF_RUN_LEGACY_WORKFLOWS },
  async () => {
    const root = process.env.AF_QUALIFIED_BROWSER_CANDIDATE;
    const prepared = process.env.AF_QUALIFIED_BROWSER_PREPARED;
    const output = process.env.AF_QUALIFIED_BROWSER_OUTPUT;
    const toolsDirectory = process.env.AF_QUALIFIED_COVERAGE_TOOLS;
    const browserDirectory = process.env.AF_QUALIFIED_BROWSER_TOOLS;
    const nodeHook = process.env.AF_QUALIFIED_BROWSER_NODE_HOOK;
    assert.ok(root && prepared && output && toolsDirectory && browserDirectory && nodeHook);
    const manifest = JSON.parse(readFileSync(resolve(prepared, 'manifest.json')));
    const generated = JSON.parse(readFileSync(resolve(prepared, 'generated.json')));
    const require = createRequire(resolve(toolsDirectory, '__qualified_entry__.cjs'));
    const parser = require('@babel/parser');
    const { chromium } = await import(pathToFileURL(resolve(browserDirectory, 'index.mjs')).href);
    const options = {
      root,
      manifest,
      generated,
      tools: { chromium, parser },
      outputDirectory: output,
      executablePath: process.env.CHROMIUM_PATH,
      browserPath: resolve(browserDirectory, 'index.mjs'),
      nodeHook,
      nodeModulesDirectory: resolve('node_modules'),
    };
    for (const [workflow, collect] of [
      ['legacy', collectLegacyBrowserCoverage],
      ['management', collectManagementBrowserCoverage],
    ]) {
      const result = await collect({ ...options, workflow });
      assert.equal(result.status, 'PASS', result.child.stderr.toString());
      assert.equal(result.child.code, 0);
      const replay = replayBrowserCoverage({
        manifest,
        outputDirectory: result.directory,
        index: result.collection.index,
      });
      assert.ok(replay.observations.some((row) => Object.keys(row.sources).length > 0));
      assert.equal(result.child.stdoutArtifact.kind, 'driver-stdout');
    }
  },
);
