import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
import {
  mkdtempSync,
  writeFileSync,
  readFileSync,
  rmSync,
  mkdirSync,
  cpSync,
  copyFileSync,
  realpathSync,
} from 'node:fs';
import { execFileSync } from 'node:child_process';
import { prepareCoverage } from '../tools/coverage/prepare.mjs';
import { collectNodeWorkflow, verifyNodeWorkflow } from '../tools/coverage/collect.mjs';
import { reportCoverage } from '../tools/coverage/report.mjs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import {
  verifyBrowserSource,
  browserCoverageSources,
  browserHelperBootstrap,
  replayBrowserCoverage,
  writeBrowserArtifact,
} from '../tools/coverage/browser-evidence.mjs';
import { createBrowserCoverageLifecycle } from '../tools/coverage/browser-lifecycle.mjs';

const directory = process.env.AF_QUALIFIED_COVERAGE_TOOLS;
const browserDirectory = process.env.AF_QUALIFIED_BROWSER_TOOLS;
assert.ok(directory && browserDirectory, 'qualified tool paths required; never silently skip');
const require = createRequire(resolve(directory, '__qualified_entry__.cjs'));
const instrument = require('istanbul-lib-instrument');
const parser = require('@babel/parser');
const { chromium } = await import(pathToFileURL(resolve(browserDirectory, 'index.mjs')).href);
const digest = (value) => createHash('sha256').update(value).digest('hex');
const sourcePath = 'choice.mjs';

function fixture(t) {
  const root = mkdtempSync(join(tmpdir(), 'alphaforge-browser-coverage-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const source = 'globalThis.choose = x => x ? 7 : 9;\n';
  const mapper = instrument.createInstrumenter({
    esModules: true,
    produceSourceMap: true,
    coverageGlobalScope: 'globalThis',
    coverageGlobalScopeFunc: false,
  });
  const code = mapper.instrumentSync(source, sourcePath);
  const coverage = structuredClone(mapper.lastFileCoverage());
  const map = mapper.lastSourceMap();
  writeFileSync(join(root, sourcePath), source);
  const manifest = {
    schemaVersion: 1,
    provider: 'LOCAL',
    candidateCommit: '1'.repeat(40),
    candidateTree: '2'.repeat(40),
    toolDigest: '3'.repeat(64),
    sources: {
      [sourcePath]: {
        sha256: digest(source),
        generatedSha256: digest(code),
        sourceMapSha256: digest(JSON.stringify(map)),
        coverage,
      },
    },
    aliases: {},
  };
  return { root, manifest, generated: { [sourcePath]: { code, map } }, coverage, code, source };
}

test('exact browser source transport rejects changed source, generated bytes and maps', (t) => {
  const f = fixture(t);
  assert.deepEqual(verifyBrowserSource({ ...f, path: sourcePath }), f.generated[sourcePath]);
  writeFileSync(join(f.root, sourcePath), 'globalThis.choose = () => 0;');
  assert.throws(() => verifyBrowserSource({ ...f, path: sourcePath }), /source/);
  writeFileSync(join(f.root, sourcePath), f.source);
  const altered = structuredClone(f.generated);
  altered[sourcePath].code += '\n';
  assert.throws(() => verifyBrowserSource({ ...f, generated: altered, path: sourcePath }), /generated/);
  altered[sourcePath].code = f.code;
  altered[sourcePath].map.sources = ['foreign.mjs'];
  assert.throws(() => verifyBrowserSource({ ...f, generated: altered, path: sourcePath }), /map/);
});

test('runtime graphs must match before prototype coordinates are translated to the canonical graph', (t) => {
  const f = fixture(t);
  const entry = f.manifest.sources[sourcePath];
  entry.runtimeCoverage = structuredClone(f.coverage);
  entry.coverage.statementMap['0'].start.line += 40;
  const observed = structuredClone(entry.runtimeCoverage);
  observed.s['0'] = 2;
  const sources = browserCoverageSources(f.manifest, { [sourcePath]: observed }, new Set([sourcePath]));
  assert.equal(sources[sourcePath].coverage.s['0'], 2);
  assert.equal(sources[sourcePath].coverage.statementMap['0'].start.line, 41);
  observed.statementMap['0'].start.column += 1;
  assert.throws(() => browserCoverageSources(f.manifest, { [sourcePath]: observed }, new Set([sourcePath])));
  assert.throws(() => browserCoverageSources(f.manifest, { foreign: f.coverage }, new Set(['foreign'])));
  assert.throws(() => browserCoverageSources(f.manifest, { [sourcePath]: f.coverage }, new Set()));
  const invalid = structuredClone(entry.runtimeCoverage);
  invalid.b['0'][0] = -1;
  assert.throws(() => browserCoverageSources(f.manifest, { [sourcePath]: invalid }, new Set([sourcePath])));
});

test('transport helpers only define the qualified source graph and preserve actual callback hits', async (t) => {
  const f = fixture(t);
  const bootstrap = browserHelperBootstrap({ ...f, parser, paths: [sourcePath] });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  t.after(() => browser.close());
  const context = await browser.newContext();
  await context.addInitScript({ content: bootstrap });
  const page = await context.newPage();
  assert.equal(await page.evaluate('globalThis.__coverage__'), undefined);
  function arrow(value) {
    if (!value || typeof value !== 'object') return undefined;
    if (value.type === 'ArrowFunctionExpression') return value;
    return Object.values(value).map(arrow).find(Boolean);
  }
  const callback = arrow(parser.parse(f.code));
  assert.equal(await page.evaluate(`(${f.code.slice(callback.start, callback.end)})(true)`), 7);
  const sources = browserCoverageSources(
    f.manifest,
    await page.evaluate('globalThis.__coverage__'),
    new Set([sourcePath]),
  );
  assert.equal(sources[sourcePath].coverage.f['0'], 1);
  assert.deepEqual(Object.values(sources[sourcePath].coverage.s), [0, 1]);
});

test('real page intervals retain zero captures and reset counters before repeated flush, reload and close', async (t) => {
  const f = fixture(t);
  const tracker = createBrowserCoverageLifecycle({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    loaded: new Set([sourcePath]),
  });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  tracker.registerPage(page);
  await page.goto('about:blank');
  await page.evaluate(`(() => { ${f.code} })()`);
  await page.evaluate('choose(true)');
  await tracker.flush(page, 'checkpoint');
  await tracker.flush(page, 'unchanged');
  await page.evaluate('choose(false)');
  await page.reload();
  await page.close();
  const result = await tracker.finish();
  const replay = replayBrowserCoverage({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    index: result.index,
  });
  assert.deepEqual(replay.observations, result.observations);
  assert.equal(replay.observations.length, 5);
  assert.equal(replay.observations[0].empty, true);
  assert.deepEqual(Object.values(replay.observations[1].sources[sourcePath].coverage.b), [[1, 0]]);
  assert.deepEqual(Object.values(replay.observations[2].sources[sourcePath].coverage.b), [[0, 0]]);
  assert.deepEqual(Object.values(replay.observations[3].sources[sourcePath].coverage.b), [[0, 1]]);
  const indexContents = JSON.parse(readFileSync(join(f.root, 'raw', result.index.file)));
  const completions = result.artifacts.filter((artifact) => artifact.kind === 'complete');
  const reused = { ...replay.observations[1], raw: replay.observations[0].raw, sources: {}, empty: true };
  const reusedRef = writeBrowserArtifact(join(f.root, 'raw'), 'complete', reused);
  const alteredIndex = writeBrowserArtifact(join(f.root, 'raw'), 'index', {
    ...indexContents,
    artifacts: indexContents.artifacts.map((ref) => (ref.file === completions[1].file ? reusedRef : ref)),
  });
  assert.throws(
    () =>
      replayBrowserCoverage({
        manifest: f.manifest,
        outputDirectory: join(f.root, 'raw'),
        index: alteredIndex,
      }),
    /raw artifact reused/,
  );
  const unflushedIndex = writeBrowserArtifact(join(f.root, 'raw'), 'index', {
    ...indexContents,
    artifacts: indexContents.artifacts.filter((ref) => ref.kind !== 'complete'),
  });
  const unflushed = replayBrowserCoverage({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    index: unflushedIndex,
  });
  assert.equal(unflushed.observations.length, 5);
  assert.ok(unflushed.observations.every((row) => !row.complete && Object.keys(row.sources).length === 0));
  const raw = result.artifacts.find((a) => a.kind === 'raw');
  writeFileSync(join(f.root, 'raw', raw.file), '[]\n');
  assert.throws(
    () =>
      replayBrowserCoverage({
        manifest: f.manifest,
        outputDirectory: join(f.root, 'raw'),
        index: result.index,
      }),
    /digest/,
  );
});

test('an unexpected page loss records incomplete zero contribution instead of silently dropping the interval', async (t) => {
  const f = fixture(t);
  const tracker = createBrowserCoverageLifecycle({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    loaded: new Set([sourcePath]),
  });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  t.after(() => browser.close());
  const context = await browser.newContext();
  const page = await context.newPage();
  tracker.registerPage(page);
  await page.evaluate(`(() => { ${f.code} })()`);
  await context.close();
  const result = await tracker.finish();
  assert.equal(result.observations.length, 1);
  assert.equal(result.observations[0].complete, false);
  assert.deepEqual(result.observations[0].sources, {});
  const replay = replayBrowserCoverage({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    index: result.index,
  });
  assert.deepEqual(replay.observations, result.observations);
  assert.ok(readFileSync(join(f.root, 'raw', result.index.file)).length);
});

test('a foreign runtime graph retains its raw failure and rejects the flush with zero contribution', async (t) => {
  const f = fixture(t);
  const tracker = createBrowserCoverageLifecycle({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    loaded: new Set([sourcePath]),
  });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  tracker.registerPage(page);
  await page.evaluate('globalThis.__coverage__ = { unexpected: {} }');
  await assert.rejects(tracker.flush(page, 'invalid-graph'), /unregistered browser graph/);
  const result = await tracker.finish();
  assert.equal(result.observations[0].complete, false);
  assert.deepEqual(result.observations[0].sources, {});
  const raw = result.observations[0].raw;
  assert.deepEqual(JSON.parse(readFileSync(join(f.root, 'raw', raw.file))), { unexpected: {} });
  const replay = replayBrowserCoverage({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    index: result.index,
  });
  assert.deepEqual(replay.observations, result.observations);
});

test('snapshot transport loss records zero and still lets the real navigation run', async (t) => {
  const f = fixture(t);
  const tracker = createBrowserCoverageLifecycle({
    manifest: f.manifest,
    outputDirectory: join(f.root, 'raw'),
    loaded: new Set([sourcePath]),
  });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  tracker.registerPage(page);
  const evaluate = page.evaluate.bind(page);
  let lost = true;
  page.evaluate = async (...args) => {
    if (lost) {
      lost = false;
      throw new Error('Execution context was destroyed during navigation');
    }
    return evaluate(...args);
  };
  await page.goto('data:text/html,<title>continued</title>');
  assert.equal(await page.title(), 'continued');
  const result = await tracker.finish();
  assert.equal(result.observations[0].complete, false);
  assert.match(result.observations[0].error.message, /Execution context was destroyed/);
  assert.doesNotThrow(() => result.index);
});

for (const scenario of ['location', 'reload', 'hash', 'history']) {
  test(`real ${scenario} navigation preserves document boundaries and conservative counters`, async (t) => {
    const f = fixture(t);
    const outputDirectory = join(f.root, 'navigation-raw');
    const tracker = createBrowserCoverageLifecycle({
      manifest: f.manifest,
      outputDirectory,
      loaded: new Set([sourcePath]),
    });
    const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
    t.after(() => browser.close());
    const page = await browser.newPage();
    page.setDefaultTimeout(8000);
    tracker.registerPage(page);
    const first = join(f.root, 'navigation-a.html');
    const second = join(f.root, 'navigation-b.html');
    writeFileSync(first, `<title>A</title><script>${f.code};choose(true);</script>`);
    writeFileSync(second, `<title>B</title><script>${f.code};choose(false);</script>`);
    await page.goto(pathToFileURL(first).href);
    if (scenario === 'location') {
      await page.evaluate((url) => {
        globalThis.location.href = url;
      }, pathToFileURL(second).href);
      await page.waitForFunction(
        () => globalThis.document.title === 'B' && typeof globalThis.choose === 'function',
      );
    } else if (scenario === 'reload') {
      await page.evaluate(() => {
        globalThis.oldRealm = true;
        globalThis.location.reload();
      });
      await page.waitForFunction(() => typeof globalThis.choose === 'function' && !globalThis.oldRealm);
    } else {
      await page.evaluate((mode) => {
        if (mode === 'hash') globalThis.location.hash = 'same-document';
        else globalThis.history.pushState({}, '', '?same-document=1');
        globalThis.choose(false);
      }, scenario);
    }
    const result = await tracker.finish();
    const replay = replayBrowserCoverage({ manifest: f.manifest, outputDirectory, index: result.index });
    assert.deepEqual(replay.observations, result.observations);
    const incomplete = result.observations.filter((row) => !row.complete);
    if (scenario === 'hash' || scenario === 'history') {
      assert.equal(incomplete.length, 0);
      assert.deepEqual(result.observations.at(-1).sources[sourcePath].coverage.b['0'], [1, 1]);
    } else {
      assert.equal(incomplete.length, 1);
      assert.equal(incomplete[0].reason, 'UNFLUSHED_NAVIGATION');
      assert.deepEqual(incomplete[0].sources, {});
      assert.deepEqual(
        result.observations.at(-1).sources[sourcePath].coverage.b['0'],
        scenario === 'location' ? [0, 1] : [1, 0],
      );
    }
  });
}

test('actual failed browser driver retains bound failure identity and replays as functional FAIL', async (t) => {
  const repository = resolve(import.meta.dirname, '..');
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'alphaforge-browser-failure-')));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const git = (...args) =>
    execFileSync('git', ['-c', 'core.hooksPath=/dev/null', '-c', 'commit.gpgsign=false', ...args], {
      cwd: root,
      encoding: 'utf8',
      env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' },
    }).trim();
  mkdirSync(join(root, 'tools'), { recursive: true });
  cpSync(join(repository, 'tools/coverage'), join(root, 'tools/coverage'), { recursive: true });
  copyFileSync(join(repository, 'tools/html-source-ranges.mjs'), join(root, 'tools/html-source-ranges.mjs'));
  cpSync(join(repository, 'node_modules'), join(root, 'node_modules'), {
    recursive: true,
    verbatimSymlinks: true,
  });
  mkdirSync(join(root, 'planning'));
  for (const file of ['coverage-toolchain.lock.json', 'coverage-instrumentation.package-lock.json'])
    copyFileSync(join(repository, 'planning', file), join(root, 'planning', file));
  for (const chunk of JSON.parse(readFileSync(join(repository, 'planning/coverage-toolchain.lock.json')))
    .instrumentation.installedFileChunks)
    copyFileSync(join(repository, chunk.path), join(root, chunk.path));
  mkdirSync(join(root, 'apps/web/prototype'), { recursive: true });
  writeFileSync(join(root, '.gitattributes'), '* text=auto eol=lf\n');
  writeFileSync(join(root, '.gitignore'), 'node_modules/\noutputs/\n');
  writeFileSync(join(root, 'package.json'), '{"type":"module"}\n');
  writeFileSync(join(root, 'apps/web/vite.config.ts'), 'export default {};\n');
  writeFileSync(
    join(root, 'apps/web/prototype/AlphaForge_v3_EN.html'),
    '<style>body{color:black}</style><script>globalThis.fixture = 1;</script>',
  );
  writeFileSync(
    join(root, 'tools/verify-m3-browser.mjs'),
    'export async function runM3BrowserJourneys() { throw new Error("ASSERTED_BROWSER_DRIVER_FAILURE"); }\n',
  );
  git('init', '-q');
  git('config', 'user.name', 'Coverage fixture');
  git('config', 'user.email', 'fixture@example.invalid');
  git('add', '.');
  git('commit', '-qm', 'bounded failure fixture');
  const options = {
    instrumentationDirectory: directory,
    browserDirectory,
    sourceBase: git('rev-parse', 'HEAD'),
  };
  const prepared = await prepareCoverage(root, options);
  const configuration = {
    id: 'm3-browser',
    args: [
      'tools/coverage/run-browser.mjs',
      '--tools',
      directory,
      '--browser-tools',
      browserDirectory,
      '--chrome',
      process.env.CHROMIUM_PATH,
      '--base',
      options.sourceBase,
      '--workflow',
      'm3',
    ],
  };
  const failed = await collectNodeWorkflow(root, prepared.directory, {
    ...options,
    ...configuration,
    timeoutMs: 60000,
    artifactFiles: ['browser-receipt.json'],
  });
  assert.equal(failed.state, 'FAIL');
  const receipt = JSON.parse(readFileSync(join(failed.directory, 'browser-receipt.json')));
  assert.equal(receipt.state, 'FAIL');
  assert.equal(receipt.workflow, 'm3');
  assert.equal(receipt.manifestSha256, prepared.manifestSha256);
  assert.equal(receipt.candidateCommit, prepared.sourceCommit);
  assert.equal(receipt.candidateTree, prepared.sourceTree);
  assert.ok(receipt.index && receipt.failure && receipt.error);
  const originalFailure = readFileSync(join(receipt.directory, receipt.failure.file));
  assert.equal(digest(originalFailure), receipt.failure.sha256);
  assert.match(originalFailure.toString(), /ASSERTED_BROWSER_DRIVER_FAILURE/);
  const measured = await reportCoverage(root, prepared.directory, {
    ...options,
    workflows: [{ ...configuration, directory: failed.directory, browser: true }],
  });
  assert.equal(measured.report.functionalState, 'FAIL');
  assert.equal(measured.report.workflows[0].state, 'FAIL');
  const manifest = JSON.parse(readFileSync(join(prepared.directory, 'manifest.json')));
  const receiptPath = join(failed.directory, 'browser-receipt.json');
  const workflowPath = join(failed.directory, 'workflow.json');
  const workflow = JSON.parse(readFileSync(workflowPath));
  for (const changed of [
    { ...receipt, workflow: 'legacy' },
    { ...receipt, manifestSha256: 'f'.repeat(64) },
    { ...receipt, index: undefined },
  ]) {
    const bytes = JSON.stringify(changed);
    writeFileSync(receiptPath, bytes);
    const record = structuredClone(workflow);
    const artifact = record.artifacts.find((item) => item.file === 'browser-receipt.json');
    artifact.sha256 = digest(bytes);
    artifact.bytes = Buffer.byteLength(bytes);
    writeFileSync(workflowPath, JSON.stringify(record));
    // Even a self-consistent artifact inventory cannot bypass cross-record binding.
    assert.equal(
      (await verifyNodeWorkflow(failed.directory, manifest, prepared.manifestSha256, configuration)).state,
      'FAIL',
    );
    await assert.rejects(
      reportCoverage(root, prepared.directory, {
        ...options,
        workflows: [{ ...configuration, directory: failed.directory, browser: true }],
      }),
    );
  }
});
